### ISSUE TITLE
Question: Sensor Template Lights

### ISSUE THREAD

**Issue by dannyhanes** [N-l1/home-assistant-config#2]
Can you share what your template sensors look like to get the counts for lights?

**Comment by Rocketman69** [comment]
I was just about to ask the same thing.

**Comment by N-l1** [comment]
Sure, here it is:  

`{{ states | selectattr('entity_id','in', ['light.add_all_your_lights_here','switch.example'] )     
|selectattr('state','eq','on') | list | count }}`
